### ISSUE TITLE
Switch to RethinkDB

### ISSUE THREAD

**Issue by basicallydan** [basicallydan/dopic#50]
## Todo:
- [x] Move over User Model
- [ ] Move over User Model Statics
- [ ] Move over User Model Methods
- [x] Move over File Model
- [ ] Move over File Model Statics
- [ ] Move over File Model Methods
- [x] Move over Album Model
- [x] Move over Album Model Statics
- [ ] Move over Album Model Methods

http://rethinkdb.com/docs/table-joins/
## Get started
- [Using with Node](http://www.rethinkdb.com/docs/nodejs/)
- [Thinky](https://github.com/neumino/thinky)
### Example

```
var thinky = require('thinky')();
var type   = thinky.type;

// Create a model - the table is automatically created
var Post = thinky.createModel("Post", {
  id: String,
  title: String,
  content: String,
  idAuthor: String
}); 

// You can also add constraints on the schema
var Author = thinky.createModel("Author", {
  id: type.string(),      // a normal string
  name: type.string().min(2),  // a string of at least two characters
  email: type.string().email()  // a string that is a valid email
});

// Join the models
Post.belongsTo(Author, "author", "idAuthor", "id");
```
